# These are supported funding model platforms

github: # https://cash.app/$kustomizing
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # https://cash.app/$kustomizing
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # https://cash.app/$kustomizing
lfx_crowdfunding: # https://cash.app/$kustomizing
custom: # https://cash.app/$kustomizing
